spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carcontrol
    username: carcontrol
    password: CcPwd23541
  #liquibase:  # can use liquibase, if db schema should be manipulated safely
   # change-log: db/changelog/db.changelog-master.yaml
  security:
    user:
      name: ekz48
      password: ekz48pwd
      roles: USER,ADMIN
  jpa:
    hibernate:
      ddl-auto: update # allow Hibernate to manipulate DB